<a href="https://colab.research.google.com/github/ai7dnn/2021-2-DNN/blob/main/code/21_1_myfirst_tf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
tf.__version__

'2.6.0'

In [2]:
import sklearn as sk
sk.__version__

'0.22.2.post1'

In [3]:
import site
site.getsitepackages()

['/usr/local/lib/python3.7/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/lib/python3.7/dist-packages']

In [4]:
a, b = 10, 20

In [5]:
a + b

30

In [6]:
x = tf.constant(10)
x

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [7]:
x

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [8]:
x.numpy()

10

In [9]:
y = tf.constant(20)
y

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [10]:
y.numpy()

20

In [11]:
x + y

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [12]:
z = x + y
z

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [13]:
z.numpy()

30

In [16]:
m = tf.constant([1, 2, 3])
m

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [17]:
m.numpy()

array([1, 2, 3], dtype=int32)

In [18]:
tf.executing_eagerly()

True

In [ ]:
# 텐서플로 1.0 버전 선택
try:
    # %tensorflow_version only exists in Colab.
    %tensorflow_version 2.x
except Exception:
    pass

import tensorflow as tf
tf.__version__

'2.5.0'

In [19]:
tf.executing_eagerly()

True

In [20]:
import tensorflow as tf

hello = tf.constant('Hello World!')
print(hello)
print(hello.numpy())

tf.Tensor(b'Hello World!', shape=(), dtype=string)
b'Hello World!'


In [22]:
a = tf.constant(5)
b = tf.constant(3)
print(a+b)
(a+b).numpy()

tf.Tensor(8, shape=(), dtype=int32)


8